name: Trading Bot

on:
  schedule:
    - cron: '0 8,20 * * *'  # Exécute tous les jours à 8h et 20h UTC
  workflow_dispatch:         # Permet de le lancer à la main depuis GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le repo
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter le bot
      run: |
        python bot_trading.py
